package com.guanxian.platform.iam;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.guanxian.platform.shared.error.ApiException;
import com.guanxian.platform.shared.error.ConflictException;
import com.guanxian.platform.shared.security.ActorScope;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.Set;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class AccessBindingServiceTest {
    private static final UUID ASSOCIATION = UUID.fromString("00000000-0000-0000-0000-000000000100");
    private static final UUID OTHER_ASSOCIATION = UUID.fromString("00000000-0000-0000-0000-000000000101");
    private static final UUID ENTERPRISE = UUID.fromString("00000000-0000-0000-0000-000000000201");
    private AccessBindingService service;
    private JdbcTemplate jdbc;

    @BeforeEach
    void setUp() {
        var dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:access-binding-" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("CREATE DOMAIN IF NOT EXISTS JSONB AS JSON");
        jdbc.execute("CREATE TABLE association (id UUID PRIMARY KEY, name VARCHAR(200), status VARCHAR(32))");
        jdbc.execute("CREATE TABLE enterprise (id UUID PRIMARY KEY, association_id UUID NOT NULL, name VARCHAR(200))");
        jdbc.execute("""
                CREATE TABLE user_account (
                  id UUID PRIMARY KEY, association_id UUID, enterprise_id UUID,
                  external_subject VARCHAR(200), username VARCHAR(100) UNIQUE,
                  display_name VARCHAR(100), email VARCHAR(254), status VARCHAR(32),
                  created_at TIMESTAMP WITH TIME ZONE, updated_at TIMESTAMP WITH TIME ZONE)
                """);
        jdbc.execute("""
                CREATE TABLE audit_log (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor_user_id UUID,
                  actor_subject VARCHAR(200), actor_username VARCHAR(100), association_id UUID,
                  enterprise_id UUID, action VARCHAR(100), resource_type VARCHAR(100),
                  resource_id VARCHAR(200), resource_version BIGINT, outcome VARCHAR(32),
                  details JSONB, request_id VARCHAR(128),
                  occurred_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)
                """);
        jdbc.update("INSERT INTO association(id, name, status) VALUES (?, '北京地下管线协会', 'ACTIVE'), (?, '友好协会', 'ACTIVE')",
                ASSOCIATION, OTHER_ASSOCIATION);
        jdbc.update("INSERT INTO enterprise(id, association_id, name) VALUES (?, ?, '绑定企业')", ENTERPRISE, ASSOCIATION);
        service = new AccessBindingService(new NamedParameterJdbcTemplate(dataSource), new ObjectMapper());
    }

    @Test
    void bindsAnExistingLocalAccountToTheExactOidcSubjectAndEnterpriseWithAudit() {
        UUID localId = UUID.randomUUID();
        jdbc.update("""
                INSERT INTO user_account(id, username, display_name, status, created_at, updated_at)
                VALUES (?, 'local.user', '旧名称', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """, localId);

        AccessBindingView created = service.upsert(new AccessBindingRequest(
                "  oidc-subject-1  ", " local.user ", " 企业管理员 ", null, ENTERPRISE, " user@example.com "), systemActor());

        assertEquals(localId, created.id());
        assertEquals("oidc-subject-1", created.externalSubject());
        assertEquals(ASSOCIATION, created.associationId());
        assertEquals(ENTERPRISE, created.enterpriseId());
        assertEquals("企业管理员", created.displayName());
        assertEquals(1, service.findAll().size());
        assertEquals("oidc-subject-1", jdbc.queryForObject(
                "SELECT external_subject FROM user_account WHERE id = ?", String.class, localId));
        assertEquals("ACCESS_BINDING_UPSERT", jdbc.queryForObject(
                "SELECT action FROM audit_log WHERE resource_id = 'oidc-subject-1'", String.class));

        AccessBindingView updated = service.upsert(new AccessBindingRequest(
                "oidc-subject-1", "local.user", "新名称", ASSOCIATION, ENTERPRISE, null), systemActor());
        assertEquals(localId, updated.id());
        assertEquals("新名称", updated.displayName());
        assertEquals(2, jdbc.queryForObject("SELECT COUNT(*) FROM audit_log", Integer.class));
    }

    @Test
    void rejectsConflictingAccountsUnknownAssociationsAndCrossAssociationEnterpriseBindings() {
        jdbc.update("""
                INSERT INTO user_account(id, external_subject, username, display_name, status, created_at, updated_at)
                VALUES (?, 'subject-one', 'same-name', '账号一', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                       (?, 'wanted-subject', 'other-name', '账号二', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """, UUID.randomUUID(), UUID.randomUUID());

        assertThrows(ConflictException.class, () -> service.upsert(new AccessBindingRequest(
                "wanted-subject", "same-name", "冲突", ASSOCIATION, null, null), systemActor()));

        ApiException missing = assertThrows(ApiException.class, () -> service.upsert(new AccessBindingRequest(
                "new-subject", "new-user", "新用户", UUID.randomUUID(), null, null), systemActor()));
        assertEquals("INVALID_ACCESS_BINDING", missing.code());

        ApiException mismatch = assertThrows(ApiException.class, () -> service.upsert(new AccessBindingRequest(
                "new-subject", "new-user", "新用户", OTHER_ASSOCIATION, ENTERPRISE, null), systemActor()));
        assertEquals("INVALID_ACCESS_BINDING", mismatch.code());
        assertEquals(2, jdbc.queryForObject("SELECT COUNT(*) FROM user_account", Integer.class));
        assertEquals(0, jdbc.queryForObject("SELECT COUNT(*) FROM audit_log", Integer.class));
    }

    private static ActorScope systemActor() {
        return new ActorScope(null, "bootstrap-subject", "system-admin", null, null,
                Set.of("SYSTEM_ADMIN"), Set.of());
    }
}
