package com.guanxian.platform.iam;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.guanxian.platform.shared.error.*;
import com.guanxian.platform.shared.security.ActorScope;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.*;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;
import org.springframework.test.util.ReflectionTestUtils;
import org.springframework.transaction.support.TransactionTemplate;
import java.nio.charset.StandardCharsets;
import java.time.*;
import java.util.*;
import java.util.function.Supplier;
import static com.guanxian.platform.iam.EnterpriseInvitations.*;
import static org.junit.jupiter.api.Assertions.*;

class EnterpriseInvitationServiceTest {
    static final UUID ASSOCIATION = UUID.randomUUID(), ENTERPRISE = UUID.randomUUID(), FOREIGN_ASSOCIATION = UUID.randomUUID(), FOREIGN_ENTERPRISE = UUID.randomUUID();
    JdbcTemplate jdbc;
    NamedParameterJdbcTemplate named;
    TransactionTemplate transactions;
    EnterpriseInvitationService service;
    EnterpriseOwnerAuthorities grants;
    static final Instant NOW = Instant.parse("2026-09-05T00:00:00Z");

    @BeforeEach void setup() throws Exception {
        var ds = new DriverManagerDataSource("jdbc:h2:mem:invites-"+UUID.randomUUID()+";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        jdbc = new JdbcTemplate(ds); named = new NamedParameterJdbcTemplate(ds);
        transactions = new TransactionTemplate(new DataSourceTransactionManager(ds));
        schema(jdbc);
        seed(jdbc);
        service = new EnterpriseInvitationService(named, new ObjectMapper(), Clock.fixed(NOW, ZoneOffset.UTC));
        grants = new EnterpriseOwnerAuthorities(named);
    }
    static void schema(JdbcTemplate jdbc) throws Exception {
        jdbc.execute("CREATE DOMAIN IF NOT EXISTS JSONB AS JSON");
        jdbc.execute("CREATE TABLE association(id UUID PRIMARY KEY,name VARCHAR(200),status VARCHAR(32))");
        jdbc.execute("CREATE TABLE enterprise(id UUID PRIMARY KEY,association_id UUID,name VARCHAR(200),status VARCHAR(32),deleted_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE user_account(id UUID PRIMARY KEY,external_subject VARCHAR(200) UNIQUE,username VARCHAR(100) UNIQUE,display_name VARCHAR(100),association_id UUID,enterprise_id UUID,status VARCHAR(32),version BIGINT DEFAULT 0,created_at TIMESTAMP WITH TIME ZONE,updated_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute("CREATE TABLE revoked_identity_subject(external_subject VARCHAR(200) PRIMARY KEY)");
        jdbc.execute("CREATE TABLE audit_log(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,actor_user_id UUID,actor_subject VARCHAR(200),actor_username VARCHAR(100),association_id UUID,enterprise_id UUID,action VARCHAR(100),resource_type VARCHAR(100),resource_id VARCHAR(200),resource_version BIGINT,outcome VARCHAR(32),details JSONB,request_id VARCHAR(128))");
        try (var input = new ClassPathResource("db/migration/V25__enterprise_owner_invitations.sql").getInputStream()) {
            String migration = new String(input.readAllBytes(), StandardCharsets.UTF_8).replace("TIMESTAMPTZ", "TIMESTAMP WITH TIME ZONE");
            var resource = new org.springframework.core.io.ByteArrayResource(migration.getBytes(StandardCharsets.UTF_8));
            new org.springframework.jdbc.datasource.init.ResourceDatabasePopulator(resource).execute(jdbc.getDataSource());
        }
    }
    static void seed(JdbcTemplate jdbc) {
        jdbc.update("INSERT INTO association VALUES(?,'本协会','ACTIVE'),(?,'其他协会','ACTIVE')", ASSOCIATION, FOREIGN_ASSOCIATION);
        jdbc.update("INSERT INTO enterprise VALUES(?,?,'既有企业','ACTIVE',NULL),(?,?,'外部企业','ACTIVE',NULL)", ENTERPRISE, ASSOCIATION, FOREIGN_ENTERPRISE, FOREIGN_ASSOCIATION);
    }
    static ActorScope admin() { return actor("reviewer", ASSOCIATION, "SYSTEM_ADMIN"); }
    static ActorScope actor(String subject, UUID association, String role) {
        return new ActorScope(null,subject,subject,association,null,Set.of(role),Set.of());
    }
    static Jwt jwt(String subject, String username) {
        return Jwt.withTokenValue("fixture-token").header("alg","RS256").subject(subject).claim("preferred_username",username).claim("name","企业负责人").build();
    }
    static JwtAuthenticationToken owner() { return new JwtAuthenticationToken(jwt("owner-subject","owner.user"), List.of(), "owner.user"); }
    <T> T tx(Supplier<T> work) { return transactions.execute(status -> work.get()); }
    Issued issue() { return tx(() -> service.create(new Create(ENTERPRISE,"owner.user"), admin())); }
    View claim(Issued invite) { return tx(() -> service.claim(new Claim(invite.token(),true),owner())); }
    View approve(View value) { return tx(() -> service.review(value.id(),value.version(),new Review("APPROVE","通过协会留存电话核验授权"),admin())); }

    @Test void fullFlowBindsExistingEnterpriseAndGrantsOnlyItsNarrowOwnerRole() {
        var issued=issue(); assertEquals(43,issued.token().length());
        assertEquals(EnterpriseInvitationService.hash(issued.token()),jdbc.queryForObject("SELECT token_hash FROM enterprise_owner_invitation",String.class));
        assertFalse(issued.toString().contains(issued.token()));
        assertFalse(grants.isOwner(owner().getToken()));
        assertEquals("ISSUED",service.preview(issued.token(),owner()).status());
        var claimed=claim(issued); assertEquals("CLAIMED",claimed.status());
        assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM user_account",Integer.class));
        assertEquals(claimed.version(),claim(issued).version());
        var approved=approve(claimed);
        assertEquals("APPROVED",approved.status()); assertEquals(2,jdbc.queryForObject("SELECT count(*) FROM enterprise",Integer.class));
        assertEquals(ENTERPRISE,jdbc.queryForObject("SELECT enterprise_id FROM user_account",UUID.class));
        assertTrue(grants.isOwner(owner().getToken()));
        SecurityConfig security = new SecurityConfig(); ReflectionTestUtils.setField(security,"enterpriseOwners",grants);
        var names=security.jwtAuthenticationConverter("preferred_username").convert(owner().getToken()).getAuthorities().stream().map(a->a.getAuthority()).toList();
        assertTrue(names.contains("ROLE_ENTERPRISE_ADMIN")); assertTrue(names.contains("ENTERPRISE_WRITE"));
        assertFalse(names.contains("ROLE_SYSTEM_ADMIN")); assertFalse(names.contains("ACCESS_BINDING_WRITE"));
        assertThrows(ApiException.class,()->claim(issued)); assertThrows(ConflictException.class,()->tx(()->service.revoke(approved.id(),approved.version(),admin())));
        assertEquals(3,jdbc.queryForObject("SELECT count(*) FROM audit_log",Integer.class));
        assertFalse(jdbc.queryForList("SELECT details FROM audit_log").toString().contains(issued.token()));
    }
    @Test void wrongUsernameAndRecreatedUsernameCannotUseTheInvitation() {
        var issued=issue();
        assertThrows(ApiException.class,()->service.preview(issued.token(),new JwtAuthenticationToken(jwt("other","wrong.user"),List.of())));
        assertThrows(ApiException.class,()->tx(()->service.claim(new Claim(issued.token(),false),owner())));
        claim(issued);
        var recreated=new JwtAuthenticationToken(jwt("recreated","owner.user"),List.of());
        assertThrows(ApiException.class,()->service.preview(issued.token(),recreated));
        assertThrows(ApiException.class,()->tx(()->service.claim(new Claim(issued.token(),true),recreated)));
        assertTrue(service.mine(recreated).isEmpty());
    }
    @Test void onlySelectedScopeMayInviteAndOnlySystemAdministratorMayReview() {
        assertThrows(ForbiddenException.class,()->tx(()->service.create(new Create(FOREIGN_ENTERPRISE,"owner.user"),admin())));
        assertThrows(ForbiddenException.class,()->service.list(actor("reviewer",null,"SYSTEM_ADMIN"),0,20));
        assertThrows(ForbiddenException.class,()->tx(()->service.create(new Create(ENTERPRISE,"owner.user"),actor("op",ASSOCIATION,"ASSOCIATION_OPERATOR"))));
        var issued=tx(()->service.create(new Create(ENTERPRISE,"owner.user"),actor("association-reviewer",ASSOCIATION,"ASSOCIATION_ADMIN")));
        var claimed=claim(issued);
        assertThrows(ForbiddenException.class,()->tx(()->service.review(claimed.id(),claimed.version(),new Review("APPROVE","核验"),actor("staff",ASSOCIATION,"ASSOCIATION_ADMIN"))));
        assertThrows(ForbiddenException.class,()->tx(()->service.review(claimed.id(),claimed.version(),new Review("APPROVE","核验"),actor("foreign",FOREIGN_ASSOCIATION,"SYSTEM_ADMIN"))));
        assertThrows(ForbiddenException.class,()->tx(()->service.review(claimed.id(),claimed.version(),new Review("APPROVE","核验"),actor("owner-subject",ASSOCIATION,"SYSTEM_ADMIN"))));
        assertTrue(service.list(actor("foreign",FOREIGN_ASSOCIATION,"SYSTEM_ADMIN"),0,20).items().isEmpty());
    }
    @Test void duplicateExpiryRevocationAndOptimisticVersionsFailClosed() {
        var issued=issue();
        assertThrows(ConflictException.class,()->issue());
        assertThrows(PreconditionFailedException.class,()->tx(()->service.revoke(issued.invitation().id(),12,admin())));
        var expired=new EnterpriseInvitationService(named,new ObjectMapper(),Clock.fixed(NOW.plusSeconds(72*3600),ZoneOffset.UTC));
        assertThrows(ApiException.class,()->expired.preview(issued.token(),owner()));
        tx(()->service.revoke(issued.invitation().id(),0,admin()));
        assertThrows(ApiException.class,()->claim(issued));
        assertNotEquals(issued.token(),issue().token());
    }
    @Test void reviewRequiresVersionAndNoteAndRejectedClaimsNeverGrantRights() {
        var claimed=claim(issue());
        assertThrows(PreconditionFailedException.class,()->tx(()->service.review(claimed.id(),0,new Review("APPROVE","核验"),admin())));
        assertThrows(ApiException.class,()->tx(()->service.review(claimed.id(),1,new Review("APPROVE","  "),admin())));
        var rejected=tx(()->service.review(claimed.id(),1,new Review("REJECT","授权证明不足"),admin()));
        assertEquals("REJECTED",rejected.status()); assertFalse(grants.isOwner(owner().getToken()));
        assertEquals("授权证明不足",service.mine(owner()).getFirst().reviewNote());
    }
    @ParameterizedTest @ValueSource(strings={"INACTIVE","FOREIGN","SUBJECT_COLLISION","UNBOUND_LOCAL"})
    void cannotOverwriteOrReactivateAnExistingAccount(String scenario) {
        var issued=issue();
        jdbc.update("INSERT INTO user_account(id,external_subject,username,association_id,enterprise_id,status) VALUES(?,?,?,?,?,?)",UUID.randomUUID(),
                scenario.equals("SUBJECT_COLLISION")?"other-subject":scenario.equals("UNBOUND_LOCAL")?null:"owner-subject","owner.user",
                scenario.equals("FOREIGN")?FOREIGN_ASSOCIATION:ASSOCIATION,scenario.equals("FOREIGN")?FOREIGN_ENTERPRISE:ENTERPRISE,scenario.equals("INACTIVE")?"INACTIVE":"ACTIVE");
        assertThrows(ApiException.class,()->claim(issued));
        assertEquals("ISSUED",jdbc.queryForObject("SELECT status FROM enterprise_owner_invitation",String.class));
        assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM enterprise_owner_grant",Integer.class));
    }
    @ParameterizedTest @ValueSource(strings={"status='INACTIVE'","version=version+1","external_subject=NULL","enterprise_id=NULL","association_id=NULL"})
    void everyRequestInvalidatesAnOldGrantWhenBindingChanges(String change) {
        approve(claim(issue())); assertTrue(grants.isOwner(owner().getToken()));
        jdbc.update("UPDATE user_account SET "+change);
        assertFalse(grants.isOwner(owner().getToken()));
    }
    @Test void revokedIdentityAndDisabledEnterpriseCannotClaimOrRetainRights() {
        approve(claim(issue()));
        jdbc.update("INSERT INTO revoked_identity_subject VALUES('owner-subject')");
        assertFalse(grants.isOwner(owner().getToken())); assertThrows(ForbiddenException.class,()->service.identity(owner()));
        jdbc.update("DELETE FROM revoked_identity_subject"); jdbc.update("UPDATE enterprise SET status='DISABLED' WHERE id=?",ENTERPRISE);
        assertFalse(grants.isOwner(owner().getToken()));
    }
    @Test void approvalRollsBackAccountAndGrantIfAuditCannotBePersisted() {
        var claimed=claim(issue());
        jdbc.execute("ALTER TABLE audit_log ADD CONSTRAINT fail_approval CHECK (action <> 'ENTERPRISE_INVITATION_APPROVED')");
        assertThrows(RuntimeException.class,()->approve(claimed));
        assertEquals("CLAIMED",jdbc.queryForObject("SELECT status FROM enterprise_owner_invitation",String.class));
        assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM user_account",Integer.class));
        assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM enterprise_owner_grant",Integer.class));
    }
}
