import { test, expect, type Page } from '@playwright/test'
async function start(page: Page, message = '查询监测企业') {
  await page.goto('/tests/ui/assistant-preview.html')
  await page.getByRole('button', { name: '打开管线智能助手' }).click()
  await page.getByLabel('向管线智能助手提问').fill(message)
  await page.getByRole('button', { name: '发送问题' }).click()
  await expect(page.locator('.assistant-trace')).toHaveCount(1)
}
const dialog = (page: Page) => page.getByRole('dialog', { name: '编辑条件并重新核对', exact: true })
const result = (page: Page) => dialog(page).getByLabel('手动条件核对结果')
const submit = (page: Page) => dialog(page).getByRole('button', { name: '按这些条件重新核对', exact: true })
async function openFirst(page: Page) { await page.getByRole('button', { name: '按条件核对这家', exact: true }).first().click() }

test('manual checks require explicit conditions, refresh current data and never send another chat', async ({ page }) => {
  await start(page); await openFirst(page)
  await expect(submit(page)).toBeDisabled()
  expect(await page.evaluate(() => window.__guanxianPreview.fitRequests.length)).toBe(0)
  await dialog(page).getByLabel('条件 1 内容', { exact: true }).fill('监测')
  await dialog(page).getByRole('button', { name: '添加条件' }).click()
  await dialog(page).getByLabel('条件 2 字段', { exact: true }).selectOption('category')
  await dialog(page).getByLabel('条件 2 内容', { exact: true }).fill('设备制造')
  await submit(page).click()
  await expect(result(page)).toContainText('登记字段支持'); await expect(result(page)).toContainText('登记值不同')
  await expect(result(page).getByRole('heading')).toBeInViewport()
  await expect(dialog(page).getByRole('button', { name: '关闭业务结果' })).toBeInViewport()
  const firstId = await result(page).locator('.fit-query-id').textContent()
  await page.screenshot({ path: '../../test-results/assistant-fit-check/desktop.png', fullPage: true })
  await dialog(page).getByLabel('条件 2 内容', { exact: true }).fill('技术服务')
  await expect(result(page)).toHaveCount(0)
  await page.evaluate(() => { window.__guanxianPreview.members[0].capabilities = ['测绘'] })
  await submit(page).click()
  await expect(result(page)).toContainText('资料不足')
  await expect(result(page).locator('.fit-query-id')).not.toHaveText(firstId!)
  expect(await page.evaluate(() => window.__guanxianPreview.requests.length)).toBe(1)
  const requests = await page.evaluate(() => window.__guanxianPreview.fitRequests)
  expect(requests[1].criteria).toEqual([{ field: 'capabilities', value: '监测' }, { field: 'category', value: '技术服务' }])
  expect(requests[1]).not.toHaveProperty('capabilities')
})

test('recommendation conditions are editable and copying keeps manual provenance and scope', async ({ page }) => {
  await page.addInitScript(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async (text: string) => { (window as unknown as { fitCopy: string }).fitCopy = text } } }))
  await start(page, '推荐企业')
  const trigger = page.getByRole('button', { name: '编辑这些条件并重新核对', exact: true })
  await trigger.click()
  await expect(dialog(page).getByLabel('条件 1 内容', { exact: true })).toHaveValue('管线监测')
  await expect(dialog(page).getByLabel('条件 2 内容', { exact: true })).toHaveValue('应急抢修')
  await dialog(page).getByLabel('条件 2 内容', { exact: true }).fill('数据服务')
  await submit(page).click(); await expect(result(page)).toContainText('资料不足')
  await dialog(page).getByRole('button', { name: '复制核对结果与依据', exact: true }).click()
  await expect(dialog(page).getByRole('button', { name: '已复制手动核对快照', exact: true })).toBeVisible()
  const copied = await page.evaluate(() => (window as unknown as { fitCopy: string }).fitCopy)
  expect(copied).toContain('查询组织上下文：'); expect(copied).toContain('条件由用户手动确认'); expect(copied).not.toContain('条件来自本轮工具参数')
  expect(copied).toContain('数据服务'); expect(copied).not.toContain('应急抢修'); expect(copied).not.toContain('测试联系人')
  await page.evaluate(() => { navigator.clipboard.writeText = async () => { throw new Error('fixture clipboard denied') } })
  await dialog(page).getByRole('button', { name: '已复制手动核对快照', exact: true }).click()
  await expect(dialog(page).getByRole('alert')).toContainText('尚未复制')
  await dialog(page).press('Escape'); await expect(dialog(page)).toHaveCount(0); await expect(trigger).toBeFocused()
})

test('mobile ordered selection, status controls, bounded table and keyboard focus work', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await start(page)
  await page.getByRole('button', { name: '加入对比', exact: true }).nth(1).click()
  await page.getByRole('button', { name: '加入对比', exact: true }).first().click()
  await page.getByRole('button', { name: '按条件核对所选企业', exact: true }).click()
  await expect(dialog(page).getByLabel('条件核对企业范围')).toContainText('所选 2 家')
  await dialog(page).getByLabel('条件 1 字段', { exact: true }).selectOption('status')
  await dialog(page).getByLabel('条件 1 内容', { exact: true }).selectOption('PENDING_REVIEW')
  await submit(page).click(); await expect(result(page)).toContainText('登记值不同')
  await expect(result(page).getByRole('heading')).toBeInViewport()
  await expect(dialog(page).getByRole('button', { name: '关闭业务结果' })).toBeInViewport()
  expect((await page.evaluate(() => window.__guanxianPreview.fitRequests))[0].enterpriseIds).toEqual(['20000000-0000-4000-8000-000000000002', '20000000-0000-4000-8000-000000000001'])
  const bounds = (await dialog(page).boundingBox())!
  expect(bounds.x).toBeGreaterThanOrEqual(0); expect(bounds.width).toBeLessThanOrEqual(390)
  expect(await dialog(page).evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: '../../test-results/assistant-fit-check/mobile.png', fullPage: true })
  await dialog(page).getByRole('button', { name: '关闭业务结果' }).focus(); await page.keyboard.press('Shift+Tab')
  await expect(dialog(page).getByRole('button', { name: '复制核对结果与依据', exact: true })).toBeFocused()
})

test('revoked records discard the entire response, malformed evidence is never shown', async ({ page }) => {
  await start(page, '推荐企业'); await page.getByRole('button', { name: '编辑这些条件并重新核对', exact: true }).click()
  await submit(page).click(); await expect(result(page)).toContainText('虚构·京华')
  await page.evaluate(() => window.__guanxianPreview.unavailableMembers.add(window.__guanxianPreview.members[1].id))
  await submit(page).click(); await expect(result(page).getByRole('alert')).toContainText('未返回任何企业的部分结果')
  await expect(result(page).locator('table')).toHaveCount(0)
  await page.evaluate(() => { window.__guanxianPreview.unavailableMembers.clear(); window.__guanxianPreview.fitMalformed = true })
  await submit(page).click(); await expect(dialog(page).getByRole('alert')).toContainText('未通过一致性检查')
  await expect(result(page)).toHaveCount(0)
})

test('cancel, close and identity change prevent delayed results from reappearing', async ({ page }) => {
  await start(page); await openFirst(page); await dialog(page).getByLabel('条件 1 内容', { exact: true }).fill('监测')
  await page.evaluate(() => { window.__guanxianPreview.fitDelayMs = 600 })
  await submit(page).click(); await dialog(page).getByRole('button', { name: '取消核对' }).click()
  await page.waitForTimeout(750); await expect(result(page)).toHaveCount(0)
  await submit(page).click(); await dialog(page).getByRole('button', { name: '关闭业务结果' }).click()
  await page.waitForTimeout(750); await expect(dialog(page)).toHaveCount(0)
  await openFirst(page); await dialog(page).getByLabel('条件 1 内容', { exact: true }).fill('监测'); await submit(page).click()
  await page.evaluate(() => window.__guanxianPreview.switchRole?.())
  await page.waitForTimeout(750); await expect(dialog(page)).toHaveCount(0)
})

test('duplicate conditions are rejected visibly, and edits clear prior results', async ({ page }) => {
  await start(page); await openFirst(page)
  await dialog(page).getByLabel('条件 1 内容', { exact: true }).fill('监测')
  await dialog(page).getByRole('button', { name: '添加条件' }).click()
  await dialog(page).getByLabel('条件 2 内容', { exact: true }).fill(' 监测 ')
  await expect(submit(page)).toBeDisabled(); await expect(dialog(page)).toContainText('请移除重复条件')
  await dialog(page).getByRole('button', { name: '删除条件 2', exact: true }).click()
  await submit(page).click(); await expect(result(page)).toBeVisible()
  await dialog(page).getByLabel('条件 1 内容', { exact: true }).fill('另一个条件')
  await expect(result(page)).toHaveCount(0)
})
