import { expect, test, type Page } from '@playwright/test'

declare global {
  interface Window {
    __workspacePreview: { go(path: string): Promise<unknown>; noAssociation(): void; switchEnterprise(): Promise<unknown> }
  }
}

async function start(page: Page) {
  await page.goto('/tests/ui/workspace-preview.html')
  await expect(page.getByRole('heading', { name: '从一个问题开始' })).toBeVisible()
  await expect(page.getByLabel('向管线智能助手提问')).toBeVisible()
}
async function send(page: Page, message: string) {
  await page.getByLabel('向管线智能助手提问').fill(message)
  await page.getByRole('button', { name: '发送问题' }).click()
}
async function fitsViewport(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual((page.viewportSize()?.width || 0) + 1)
}

test('association home is a conversation canvas with real module links and a compact model icon', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await start(page)
  const canvas = page.getByRole('region', { name: '管线智能助手' })
  await expect(canvas).toBeVisible()
  await expect(page.locator('.assistant-launcher, .model-access-launcher')).toHaveCount(0)
  await expect(canvas.getByRole('button', { name: '打开个人模型接入' })).toBeVisible()
  await expect(page.getByRole('button', { name: '发送问题' })).toBeDisabled()
  const links = page.getByRole('navigation', { name: '常用业务入口' }).getByRole('link')
  await expect(links).toHaveCount(4)
  expect(await links.evaluateAll(items => items.map(item => item.getAttribute('href')))).toEqual(['/members', '/policies', '/ecosystem', '/collaborations'])
  expect(await page.evaluate(() => window.__guanxianPreview.requests.length)).toBe(0)
  await fitsViewport(page)
  await page.screenshot({ path: info.outputPath('workspace-desktop.png'), fullPage: true, animations: 'disabled' })
  await page.locator('.workspace-overview > summary').click()
  await expect(page.getByText('当前没有待办事项', { exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('same conversation and draft move between workspace and right-corner robot without automatic sending', async ({ page }, info) => {
  await start(page)
  await send(page, '查询监测企业')
  await expect(page.locator('.assistant-trace')).toHaveCount(1)
  await page.getByLabel('向管线智能助手提问').fill('这个草稿先不要发送')
  await page.locator('.main-nav').getByRole('link', { name: '会员企业', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '管线智能助手' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '打开个人模型接入' })).toHaveCount(0)
  const robot = page.getByRole('button', { name: '打开管线智能助手' })
  const box = await robot.boundingBox()
  expect(box!.x).toBeGreaterThan((page.viewportSize()?.width || 0) - 90)
  await robot.click()
  await expect(page.locator('.assistant-trace')).toHaveCount(1)
  await expect(page.getByLabel('向管线智能助手提问')).toHaveValue('这个草稿先不要发送')
  await page.screenshot({ path: info.outputPath('floating-desktop.png'), fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: '关闭智能助手', exact: true }).click()
  await expect(robot).toBeFocused()
  await page.locator('.main-nav').getByRole('link', { name: '协会工作台', exact: true }).click()
  await expect(page.getByRole('region', { name: '管线智能助手' })).toBeVisible()
  await expect(page.getByLabel('向管线智能助手提问')).toHaveValue('这个草稿先不要发送')
  expect(await page.evaluate(() => window.__guanxianPreview.requests.length)).toBe(1)
  const firstId = await page.evaluate(() => window.__guanxianPreview.requests[0].conversationId)
  await send(page, '再查一次会员企业')
  await expect(page.locator('.assistant-trace')).toHaveCount(2)
  expect(await page.evaluate(() => window.__guanxianPreview.requests[1].conversationId)).toBe(firstId)
})

test('model dialog closes back to its header icon and never loses a draft or exposes unsaved key', async ({ page }) => {
  await start(page)
  await page.getByLabel('向管线智能助手提问').fill('保留我的提问')
  const modelIcon = page.getByRole('button', { name: '打开个人模型接入' })
  await modelIcon.click()
  await expect(page.getByRole('dialog', { name: '模型接入' })).toBeVisible()
  await expect(page.locator('#platform-chat-assistant')).toHaveAttribute('inert', '')
  await page.locator('#personal-model-key').fill('unsaved-fixture-key')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: '模型接入' })).toHaveCount(0)
  await expect(modelIcon).toBeFocused()
  await expect(page.getByLabel('向管线智能助手提问')).toHaveValue('保留我的提问')
  expect(await page.evaluate(() => JSON.stringify({ ...localStorage, ...sessionStorage }))).not.toContain('unsaved-fixture-key')
  await modelIcon.click()
  await expect(page.locator('#personal-model-key')).toHaveValue('')
  await page.getByRole('button', { name: '关闭模型接入' }).click()
  await page.evaluate(() => window.__workspacePreview.go('/members'))
  await page.getByRole('button', { name: '打开管线智能助手' }).click()
  await modelIcon.click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: '管线智能助手', exact: true })).toBeVisible()
  await expect(modelIcon).toBeFocused()
})

test('mobile canvas and expandable robot fit the screen, including response settings and model dialog', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await start(page)
  await fitsViewport(page)
  await page.screenshot({ path: info.outputPath('workspace-mobile.png'), fullPage: true, animations: 'disabled' })
  await page.evaluate(() => window.__workspacePreview.go('/members'))
  const robot = page.getByRole('button', { name: '打开管线智能助手' })
  await robot.focus()
  await page.keyboard.press('Enter')
  const panel = page.getByRole('dialog', { name: '管线智能助手' })
  const box = await panel.boundingBox()
  expect(box!.x).toBeGreaterThanOrEqual(0)
  expect(box!.x + box!.width).toBeLessThanOrEqual(390)
  expect(box!.y).toBeGreaterThanOrEqual(0)
  expect(box!.y + box!.height).toBeLessThanOrEqual(844)
  await page.getByText('回答设置 · 自动详略').click()
  await expect(page.getByLabel('输出详略', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '打开个人模型接入' }).click()
  await expect(page.getByRole('dialog', { name: '模型接入' })).toBeVisible()
  await page.keyboard.press('Escape')
  await fitsViewport(page)
  await page.screenshot({ path: info.outputPath('floating-mobile.png'), fullPage: true, animations: 'disabled' })
  await page.keyboard.press('Escape')
  await expect(robot).toBeFocused()
})

test('scope and identity changes discard prior conversation, and an unselected association cannot send', async ({ page }) => {
  await start(page)
  await send(page, '测试停止')
  await expect(page.getByText('正在输出 · 内容尚未完成')).toBeVisible()
  await page.evaluate(() => window.__workspacePreview.noAssociation())
  await expect(page.getByLabel('向管线智能助手提问')).toBeDisabled()
  await expect(page.getByRole('button', { name: '发送问题' })).toBeDisabled()
  await expect(page.locator('.assistant-message.user')).toHaveCount(0)
  await expect(page.locator('.assistant-trace')).toHaveCount(0)
  await page.evaluate(() => window.__workspacePreview.switchEnterprise())
  await expect(page.locator('.assistant-workspace')).toHaveCount(0)
  await page.getByRole('button', { name: '打开管线智能助手' }).click()
  await expect(page.locator('.assistant-message.user')).toHaveCount(0)
  expect(await page.evaluate(() => window.__guanxianPreview.requests.length)).toBe(1)
})

test('a narrow-screen stream survives navigation and remains stoppable from the expanded robot', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await start(page)
  await send(page, '测试停止')
  await expect(page.getByText('正在输出 · 内容尚未完成')).toBeVisible()
  await fitsViewport(page)
  await page.evaluate(() => window.__workspacePreview.go('/members'))
  await page.getByRole('button', { name: '打开管线智能助手' }).click()
  await expect(page.getByText('正在输出 · 内容尚未完成')).toBeVisible()
  const stop = page.getByRole('button', { name: '停止回答' })
  await expect(stop).toBeInViewport()
  await stop.click()
  await expect(page.getByText('已停止，以上为未完成内容。')).toBeVisible()
  expect(await page.evaluate(() => window.__guanxianPreview.requests.length)).toBe(1)
  await fitsViewport(page)
})
