import { test, expect, type Page } from '@playwright/test'
const firstId = '20000000-0000-4000-8000-000000000001'
async function send(page: Page, message: string) {
  await page.getByLabel('向管线智能助手提问').fill(message)
  await page.getByRole('button', { name: '发送问题' }).click()
}
async function start(page: Page) {
  await page.goto('/tests/ui/assistant-preview.html')
  await page.getByRole('button', { name: '打开管线智能助手' }).click()
  await send(page, '查询监测企业')
  await expect(page.locator('.assistant-trace')).toHaveCount(1)
}
test('a visible selection survives followups, refreshes labels and never sends automatically', async ({ page }) => {
  await start(page)
  await page.getByRole('button', { name: '追问这家', exact: true }).first().click()
  const scope = page.getByLabel('追问企业范围')
  await expect(scope).toContainText('虚构·京华监测科技')
  expect(await page.evaluate(() => window.__guanxianPreview.requests.length)).toBe(1)
  await page.screenshot({ path: '../../test-results/assistant-followup/selection.png', fullPage: true })
  await send(page, '它现在有什么能力？')
  await expect(page.locator('.assistant-trace')).toHaveCount(2)
  await page.evaluate(() => { window.__guanxianPreview.members[0].name = '虚构·京华监测科技（已更新）' })
  await send(page, '这些信息还是最新的吗？')
  await expect(page.locator('.assistant-trace')).toHaveCount(3)
  await expect(scope).toContainText('已更新')
  const requests = await page.evaluate(() => window.__guanxianPreview.requests)
  expect(requests[1].selectedEnterpriseIds).toEqual([firstId])
  expect(requests[2].selectedEnterpriseIds).toEqual([firstId])
  expect(requests[1]).not.toHaveProperty('selectedEnterprises')
  await page.getByRole('button', { name: '清除选择', exact: true }).click()
  await expect(scope).toHaveCount(0)
  await send(page, '换个话题')
  await expect(page.locator('.assistant-trace')).toHaveCount(4)
  expect((await page.evaluate(() => window.__guanxianPreview.requests)).at(-1)!.selectedEnterpriseIds).toEqual([])
})
test('two selected companies retain explicit order and existing draft text on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await start(page)
  await page.getByLabel('向管线智能助手提问').fill('我已有草稿，请保留')
  await page.getByRole('button', { name: '加入对比', exact: true }).nth(1).click()
  await page.getByRole('button', { name: '加入对比', exact: true }).first().click()
  await page.getByRole('button', { name: '追问所选企业', exact: true }).click()
  await expect(page.getByLabel('向管线智能助手提问')).toHaveValue('我已有草稿，请保留')
  const scope = page.getByLabel('追问企业范围')
  await expect(scope).toContainText('正在追问 2 家企业')
  await page.screenshot({ path: '../../test-results/assistant-followup/mobile-selection.png', fullPage: true })
  const composer = (await page.getByLabel('向管线智能助手提问').boundingBox())!
  expect(composer.width).toBeGreaterThan(200)
  expect(composer.x + composer.width).toBeLessThanOrEqual(390)
  await send(page, '这两家的差异是什么？')
  await expect(page.locator('.assistant-trace')).toHaveCount(2)
  const requests = await page.evaluate(() => window.__guanxianPreview.requests)
  expect(requests[1].selectedEnterpriseIds).toEqual(['20000000-0000-4000-8000-000000000002', firstId])
  await expect(page.getByRole('button', { name: '打开对比表（重新查询）', exact: true })).toBeVisible()
})
test('permission changes and old servers do not silently reuse old company facts', async ({ page }) => {
  await start(page)
  await page.getByRole('button', { name: '追问这家', exact: true }).first().click()
  await page.evaluate(id => window.__guanxianPreview.unavailableMembers.add(id), firstId)
  await send(page, '它现在怎么样？')
  await expect(page.locator('.assistant-message.assistant').last()).toContainText('未沿用旧企业资料')
  await expect(page.locator('.assistant-message.assistant').last().locator('.business-card')).toHaveCount(0)
  await expect(page.locator('.assistant-trace')).toHaveCount(2)
  await send(page, '测试旧版服务')
  await expect(page.getByRole('alert')).toContainText('未核验所选企业')
  await expect(page.locator('.assistant-message.assistant').last()).not.toContainText('本地模拟：所选资料')
})
test('retry restores the original selected company; clearing and role change erase selection', async ({ page }) => {
  await start(page)
  await page.getByRole('button', { name: '追问这家', exact: true }).first().click()
  await send(page, '所选企业断流')
  await expect(page.getByRole('alert')).toBeVisible()
  await page.getByRole('button', { name: '清除选择', exact: true }).click()
  await page.getByRole('button', { name: '重新回答（新会话）', exact: true }).click()
  await expect(page.locator('.assistant-trace')).toHaveCount(2)
  await expect(page.getByLabel('追问企业范围')).toContainText('京华')
  expect((await page.evaluate(() => window.__guanxianPreview.requests)).at(-1)!.selectedEnterpriseIds).toEqual([firstId])
  await page.evaluate(() => window.__guanxianPreview.switchRole?.())
  await expect(page.getByLabel('追问企业范围')).toHaveCount(0)
  await expect(page.locator('.business-results')).toHaveCount(0)
})
test('copy includes query evidence and reports clipboard denial without false success', async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async (text: string) => { (window as unknown as { copiedFixture: string }).copiedFixture = text } } })
  })
  await start(page)
  await page.getByRole('button', { name: '复制结果与依据', exact: true }).click()
  await expect(page.getByRole('button', { name: '已复制查询快照', exact: true })).toBeVisible()
  const copied = await page.evaluate(() => (window as unknown as { copiedFixture: string }).copiedFixture)
  expect(copied).toContain('查询编号：'); expect(copied).toContain('查询范围：'); expect(copied).toContain('查询时间：')
  expect(copied).toContain('共 12 条，展示 3 条'); expect(copied).not.toContain('测试联系人')
  await page.evaluate(() => { navigator.clipboard.writeText = async () => { throw new Error('fixture denied') } })
  await page.getByRole('button', { name: '已复制查询快照', exact: true }).click()
  await expect(page.locator('.business-results [role=alert]')).toContainText('尚未复制到剪贴板')
  await expect(page.getByRole('button', { name: '已复制查询快照', exact: true })).toHaveCount(0)
})
