package com.guanxian.platform.member.internal;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.guanxian.platform.shared.error.ForbiddenException;
import com.guanxian.platform.shared.security.ActorScope;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.Map;
import java.util.Set;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class AuditTrailScopeTest {
    private static final UUID ASSOCIATION_A =
            UUID.fromString("00000000-0000-0000-0000-000000000101");
    private static final UUID ASSOCIATION_B =
            UUID.fromString("00000000-0000-0000-0000-000000000102");
    private static final UUID ENTERPRISE_A =
            UUID.fromString("00000000-0000-0000-0000-000000000201");
    private static final UUID ENTERPRISE_A2 =
            UUID.fromString("00000000-0000-0000-0000-000000000202");
    private static final UUID ENTERPRISE_B =
            UUID.fromString("00000000-0000-0000-0000-000000000203");

    @Test
    void inMemoryAuditReadsRespectSelectedAssociationAndEnterprise() {
        AuditTrail trail = new InMemoryAuditTrail();
        record(trail, ASSOCIATION_A, ENTERPRISE_A, "A1");
        record(trail, ASSOCIATION_A, ENTERPRISE_A2, "A2");
        record(trail, ASSOCIATION_B, ENTERPRISE_B, "B");
        assertScopes(trail);
    }

    @Test
    void postgresAuditReadsRespectSelectedAssociationAndEnterprise() {
        var dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:audit-scope-" + UUID.randomUUID()
                        + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa",
                "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("CREATE DOMAIN IF NOT EXISTS JSONB AS VARCHAR");
        jdbc.execute("""
                CREATE TABLE user_account (
                    id UUID PRIMARY KEY,
                    external_subject VARCHAR(200))
                """);
        jdbc.execute("""
                CREATE TABLE audit_log (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    actor_user_id UUID,
                    actor_subject VARCHAR(200),
                    actor_username VARCHAR(100),
                    association_id UUID,
                    enterprise_id UUID,
                    action VARCHAR(100),
                    resource_type VARCHAR(100),
                    resource_id VARCHAR(200),
                    resource_version BIGINT,
                    outcome VARCHAR(32),
                    details JSONB,
                    request_id VARCHAR(128),
                    occurred_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)
                """);
        insertAudit(jdbc, ASSOCIATION_A, ENTERPRISE_A, "A1");
        insertAudit(jdbc, ASSOCIATION_A, ENTERPRISE_A2, "A2");
        insertAudit(jdbc, ASSOCIATION_B, ENTERPRISE_B, "B");
        assertScopes(new PostgresAuditTrail(
                new NamedParameterJdbcTemplate(dataSource), new ObjectMapper()));
    }

    private static void assertScopes(AuditTrail trail) {
        assertEquals(3, trail.findVisible(system(null, null), null, 20).size());
        assertEquals(Set.of("A1", "A2"),
                resourceIds(trail.findVisible(system(ASSOCIATION_A, null), null, 20)));
        assertEquals(Set.of("A1"),
                resourceIds(trail.findVisible(
                        system(ASSOCIATION_A, ENTERPRISE_A), null, 20)));
        assertEquals(Set.of(),
                resourceIds(trail.findVisible(
                        system(ASSOCIATION_A, null), ENTERPRISE_B, 20)));
        assertThrows(ForbiddenException.class, () -> trail.findVisible(
                system(ASSOCIATION_A, ENTERPRISE_A), ENTERPRISE_A2, 20));
    }

    private static void insertAudit(
            JdbcTemplate jdbc, UUID associationId, UUID enterpriseId, String resourceId) {
        jdbc.update("""
                INSERT INTO audit_log (
                    actor_subject, actor_username, association_id, enterprise_id,
                    action, resource_type, resource_id, resource_version,
                    outcome, details, request_id)
                VALUES (?, ?, ?, ?, 'TEST', 'ENTERPRISE', ?, 0,
                        'SUCCESS', CAST('{}' AS jsonb), 'test')
                """, "writer-" + resourceId, "writer", associationId, enterpriseId, resourceId);
    }

    private static void record(
            AuditTrail trail, UUID associationId, UUID enterpriseId, String resourceId) {
        trail.record(
                new ActorScope(
                        UUID.randomUUID(), "writer-" + resourceId, "writer",
                        associationId, enterpriseId, Set.of("ASSOCIATION_ADMIN"), Set.of()),
                "TEST",
                "ENTERPRISE",
                resourceId,
                associationId,
                enterpriseId,
                Map.of("newVersion", 0));
    }

    private static Set<String> resourceIds(java.util.List<AuditRecord> records) {
        return records.stream().map(AuditRecord::resourceId)
                .collect(java.util.stream.Collectors.toSet());
    }

    private static ActorScope system(UUID associationId, UUID enterpriseId) {
        return new ActorScope(
                UUID.randomUUID(), "system", "system",
                associationId, enterpriseId, Set.of("SYSTEM_ADMIN"), Set.of());
    }
}
