package com.guanxian.platform.member.internal;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.guanxian.platform.shared.error.ForbiddenException;
import com.guanxian.platform.shared.security.ActorScope;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.Map;
import java.util.Set;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class AuditTrailScopeTest {
    private static final UUID ASSOCIATION_A =
            UUID.fromString("00000000-0000-0000-0000-000000000101");
    private static final UUID ASSOCIATION_B =
            UUID.fromString("00000000-0000-0000-0000-000000000102");
    private static final UUID ENTERPRISE_A =
            UUID.fromString("00000000-0000-0000-0000-000000000201");
    private static final UUID ENTERPRISE_A2 =
            UUID.fromString("00000000-0000-0000-0000-000000000202");
    private static final UUID ENTERPRISE_B =
            UUID.fromString("00000000-0000-0000-0000-000000000203");

    @Test
    void inMemoryAuditReadsRespectSelectedAssociationAndEnterprise() {
        AuditTrail trail = new InMemoryAuditTrail();
        record(trail, ASSOCIATION_A, ENTERPRISE_A, "A1");
        record(trail, ASSOCIATION_A, ENTERPRISE_A2, "A2");
        record(trail, ASSOCIATION_B, ENTERPRISE_B, "B");
        assertScopes(trail, () -> record(trail, ASSOCIATION_A, ENTERPRISE_A, "A3"));

        trail.recordReview(
                writer(ASSOCIATION_A, ENTERPRISE_A), ASSOCIATION_A, ENTERPRISE_A,
                7, "PENDING_REVIEW", "ACTIVE", "资料通过");
        AuditRecord review = trail.findVisible(
                        system(ASSOCIATION_A, ENTERPRISE_A), ENTERPRISE_A, 20).stream()
                .filter(record -> "MEMBER_REVIEW".equals(record.action()))
                .findFirst().orElseThrow();
        assertEquals(Long.valueOf(7), review.resourceVersion());
        assertEquals(7L, ((Number) review.details().get("newVersion")).longValue());
    }

    @Test
    void postgresAuditReadsRespectSelectedAssociationAndEnterprise() {
        var dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:audit-scope-" + UUID.randomUUID()
                        + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa",
                "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("CREATE DOMAIN IF NOT EXISTS JSONB AS VARCHAR");
        jdbc.execute("""
                CREATE TABLE user_account (
                    id UUID PRIMARY KEY,
                    external_subject VARCHAR(200))
                """);
        jdbc.execute("""
                CREATE TABLE audit_log (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    actor_user_id UUID,
                    actor_subject VARCHAR(200),
                    actor_username VARCHAR(100),
                    association_id UUID,
                    enterprise_id UUID,
                    action VARCHAR(100),
                    resource_type VARCHAR(100),
                    resource_id VARCHAR(200),
                    resource_version BIGINT,
                    outcome VARCHAR(32),
                    details JSONB,
                    request_id VARCHAR(128),
                    occurred_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)
                """);
        jdbc.execute("""
                CREATE TABLE member_review (
                    enterprise_id UUID,
                    reviewer_user_id UUID,
                    reviewer_subject VARCHAR(200),
                    previous_status VARCHAR(32),
                    decision VARCHAR(32),
                    comment VARCHAR(2000))
                """);
        insertAudit(jdbc, ASSOCIATION_A, ENTERPRISE_A, "A1");
        insertAudit(jdbc, ASSOCIATION_A, ENTERPRISE_A2, "A2");
        insertAudit(jdbc, ASSOCIATION_B, ENTERPRISE_B, "B");
        AuditTrail trail = new PostgresAuditTrail(
                new NamedParameterJdbcTemplate(dataSource), new ObjectMapper());
        assertScopes(trail, () -> insertAudit(jdbc, ASSOCIATION_A, ENTERPRISE_A, "A3"));

        trail.recordReview(
                writer(ASSOCIATION_A, ENTERPRISE_A), ASSOCIATION_A, ENTERPRISE_A,
                8, "PENDING_REVIEW", "ACTIVE", "资料通过");
        assertEquals(Long.valueOf(8), jdbc.queryForObject("""
                SELECT resource_version FROM audit_log
                 WHERE action='MEMBER_REVIEW' AND enterprise_id=?
                """, Long.class, ENTERPRISE_A));
    }

    private static void assertScopes(AuditTrail trail, Runnable appendAudit) {
        assertEquals(3, trail.findVisible(system(null, null), null, 20).size());
        AuditPage firstPage = trail.pageVisible(system(null, null), null, 0, 2);
        AuditPage secondPage = trail.pageVisible(system(null, null), null, 1, 2);
        assertEquals(3, firstPage.total());
        assertEquals(2, firstPage.items().size());
        assertEquals(1, secondPage.items().size());
        assertEquals(1, secondPage.page());
        assertEquals(2, secondPage.size());
        assertEquals(2, trail.pageVisible(system(ASSOCIATION_A, null), null, 0, 20).total());
        assertEquals(Set.of("A1", "A2"),
                resourceIds(trail.findVisible(system(ASSOCIATION_A, null), null, 20)));
        assertEquals(Set.of("A1"),
                resourceIds(trail.findVisible(
                        system(ASSOCIATION_A, ENTERPRISE_A), null, 20)));
        assertEquals(Set.of(),
                resourceIds(trail.findVisible(
                        system(ASSOCIATION_A, null), ENTERPRISE_B, 20)));
        assertThrows(ForbiddenException.class, () -> trail.findVisible(
                system(ASSOCIATION_A, ENTERPRISE_A), ENTERPRISE_A2, 20));

        appendAudit.run();
        AuditPage stableSecondPage = trail.pageVisible(
                system(null, null), null, 1, 2, firstPage.snapshotId());
        assertEquals(3, stableSecondPage.total());
        assertEquals(Set.of("A1"), resourceIds(stableSecondPage.items()));
        assertEquals(4, trail.pageVisible(system(null, null), null, 0, 2).total());
    }

    private static void insertAudit(
            JdbcTemplate jdbc, UUID associationId, UUID enterpriseId, String resourceId) {
        jdbc.update("""
                INSERT INTO audit_log (
                    actor_subject, actor_username, association_id, enterprise_id,
                    action, resource_type, resource_id, resource_version,
                    outcome, details, request_id)
                VALUES (?, ?, ?, ?, 'TEST', 'ENTERPRISE', ?, 0,
                        'SUCCESS', CAST('{}' AS jsonb), 'test')
                """, "writer-" + resourceId, "writer", associationId, enterpriseId, resourceId);
    }

    private static void record(
            AuditTrail trail, UUID associationId, UUID enterpriseId, String resourceId) {
        trail.record(
                new ActorScope(
                        UUID.randomUUID(), "writer-" + resourceId, "writer",
                        associationId, enterpriseId, Set.of("ASSOCIATION_ADMIN"), Set.of()),
                "TEST",
                "ENTERPRISE",
                resourceId,
                associationId,
                enterpriseId,
                Map.of("newVersion", 0));
    }

    private static Set<String> resourceIds(java.util.List<AuditRecord> records) {
        return records.stream().map(AuditRecord::resourceId)
                .collect(java.util.stream.Collectors.toSet());
    }

    private static ActorScope system(UUID associationId, UUID enterpriseId) {
        return new ActorScope(
                UUID.randomUUID(), "system", "system",
                associationId, enterpriseId, Set.of("SYSTEM_ADMIN"), Set.of());
    }

    private static ActorScope writer(UUID associationId, UUID enterpriseId) {
        return new ActorScope(
                UUID.randomUUID(), "reviewer", "reviewer",
                associationId, enterpriseId, Set.of("ASSOCIATION_ADMIN"), Set.of());
    }
}
